# Generated by Django 5.1.4 on 2024-12-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOfficeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название статуса филиала')),
            ],
            options={
                'verbose_name': 'Статус филиала',
                'verbose_name_plural': 'Статусы филиалов',
            },
        ),
        migrations.CreateModel(
            name='BranchOfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название типа филиала')),
            ],
            options={
                'verbose_name': 'Тип филиала',
                'verbose_name_plural': 'Типы филиалов',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ITN', models.CharField(max_length=10, verbose_name='ИНН')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы компаний')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Группа компаний',
                'verbose_name_plural': 'Группы компаний',
            },
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=None, max_length=11, null=True, verbose_name='Телефон филиала')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Примечания')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Test.branchofficestatus', verbose_name='Статус филиала')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.branchofficetype', verbose_name='Тип филиала')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='Test.company', verbose_name='Принадлежит к компании')),
            ],
            options={
                'verbose_name': 'Филиал компании',
                'verbose_name_plural': 'Филиалы компании',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='companyGroup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies', to='Test.companygroup', verbose_name='Принадлежит к группе компаний'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название должности')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Примечания')),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='Test.company', verbose_name='Должности в компании')),
            ],
            options={
                'verbose_name': 'Должность в компании',
                'verbose_name_plural': 'Должности компании',
            },
        ),
    ]
