# Generated by Django 5.1.4 on 2024-12-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='Test.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.branchofficetype', verbose_name='Тип филиала'),
        ),
        migrations.AlterField(
            model_name='branchofficestatus',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Название статуса филиала'),
        ),
        migrations.AlterField(
            model_name='branchofficetype',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Название типа филиала'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ITN',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примечания'),
        ),
        migrations.CreateModel(
            name='BranchOfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(default='', max_length=20, verbose_name='Улица')),
                ('building', models.CharField(default='', max_length=20, verbose_name='Строение\\здание')),
                ('floor', models.IntegerField(default=0, null=True, verbose_name='Этаж')),
                ('room', models.CharField(default='', max_length=5, verbose_name='Помещение')),
                ('branchOffice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='locations', to='Test.branchoffice', verbose_name='Локация филиала')),
            ],
        ),
        migrations.CreateModel(
            name='BranchOfficeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('branchOffice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='Test.branchoffice', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Расписание филиала',
                'verbose_name_plural': 'Расписания филиалов',
                'unique_together': {('branchOffice', 'day_of_week')},
            },
        ),
    ]
