# Generated by Django 5.1.4 on 2024-12-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_branchoffice_company_alter_branchoffice_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchofficelocation',
            options={'verbose_name': 'Адрес филиала', 'verbose_name_plural': 'Адреса филиала'},
        ),
        migrations.RenameField(
            model_name='branchofficelocation',
            old_name='streetName',
            new_name='street',
        ),
        migrations.AlterModelTable(
            name='branchoffice',
            table='BranchOffice',
        ),
        migrations.AlterModelTable(
            name='branchofficelocation',
            table='BranchOfficeLocation',
        ),
        migrations.AlterModelTable(
            name='branchofficeschedule',
            table='BranchOfficeSchedule',
        ),
        migrations.AlterModelTable(
            name='branchofficestatus',
            table='BranchOfficeStatus',
        ),
        migrations.AlterModelTable(
            name='branchofficetype',
            table='BranchOfficeType',
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='companygroup',
            table='CompanyGroup',
        ),
        migrations.AlterModelTable(
            name='position',
            table='Position',
        ),
    ]
