# Generated by Django 5.1.4 on 2024-12-14 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_individualentity_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='Test.company', verbose_name='Компания'),
        ),
    ]
