# Generated by Django 5.1.4 on 2024-12-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_alter_position_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль учётной записи',
                'verbose_name_plural': 'Роли учётной записи',
                'db_table': 'AccountRole',
            },
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус учётной записи',
                'verbose_name_plural': 'Статусы учётной записи',
                'db_table': 'AccountStatus',
            },
        ),
        migrations.RenameField(
            model_name='account',
            old_name='individual',
            new_name='individual_entity',
        ),
        migrations.CreateModel(
            name='AccountOfBranchEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.account', verbose_name='Учётная запись')),
                ('branchOffice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.branchoffice', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'M2M Учётка-Филиал',
                'verbose_name_plural': 'M2M Учётка-Филиал',
                'db_table': 'AccountOfBranchEmployees',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='branchOffices',
            field=models.ManyToManyField(related_name='employees_accounts', through='Test.AccountOfBranchEmployees', to='Test.branchoffice', verbose_name='Филиалы'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.accountrole', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.accountstatus', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CompanyGroupDecisionMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyGroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.companygroup', verbose_name='Группа компаний')),
                ('decisionMaker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.individualentity', verbose_name='ЛПР')),
            ],
            options={
                'verbose_name': 'M2M Группа компаний - ЛПР',
                'verbose_name_plural': 'M2M Группа компаний - ЛПР',
                'db_table': 'CompanyGroupDecisionMaker',
            },
        ),
        migrations.AddField(
            model_name='companygroup',
            name='decisionMaker',
            field=models.ManyToManyField(related_name='decision_maker_in_companies', through='Test.CompanyGroupDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
    ]
