# Generated by Django 5.1.4 on 2024-12-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_accountrole_accountstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygroup',
            name='decisionMaker',
            field=models.ManyToManyField(related_name='decision_maker_in_company_groups', through='Test.CompanyGroupDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
        migrations.CreateModel(
            name='CompanyDecisionMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.company', verbose_name='Компания')),
                ('decisionMaker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.individualentity', verbose_name='ЛПР')),
            ],
            options={
                'verbose_name': 'M2M Компания - ЛПР',
                'verbose_name_plural': 'M2M Компания - ЛПР',
                'db_table': 'CompanyDecisionMaker',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='decisionMaker',
            field=models.ManyToManyField(related_name='decision_maker_in_companies', through='Test.CompanyDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
    ]
