# Generated by Django 5.1.4 on 2024-12-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_alter_companygroup_decisionmaker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePlacementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Тип размещения оборудования',
                'verbose_name_plural': 'Типы размещения оборудования',
                'db_table': 'DevicePlacementType',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'DeviceType',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название программного обеспечения')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Закупочная цена')),
                ('license_key', models.CharField(default=None, max_length=200, null=True, verbose_name='Лицензионный ключ')),
                ('purchaseDate', models.DateField(default=None, null=True, verbose_name='Дата покупки')),
                ('licenseActivationDate', models.DateField(default=None, null=True, verbose_name='Дата активации лицензии')),
                ('licenseExpirationDate', models.DateField(default=None, null=True, verbose_name='Дата окончания лицензии')),
            ],
            options={
                'verbose_name': 'Программное обеспечение',
                'verbose_name_plural': 'Программное обеспечение',
                'db_table': 'Software',
            },
        ),
        migrations.CreateModel(
            name='SoftwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип программного обеспечения')),
            ],
            options={
                'verbose_name': 'Тип программного обеспечения',
                'verbose_name_plural': 'Типы программного обеспечения',
                'db_table': 'SoftwareType',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventoryNumber', models.CharField(default=None, max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('factoryNumber', models.CharField(default=None, max_length=20, null=True, verbose_name='Заводской номер')),
                ('branchOfficeLocation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='Test.branchofficelocation', verbose_name='Локация')),
                ('responsiblePerson', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='Test.individualentity', verbose_name='Ответственное лицо')),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Test.deviceplacementmethod', verbose_name='Метод размещения')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.devicetype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'Device',
            },
        ),
    ]
