# Generated by Django 5.1.4 on 2024-12-14 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_hardwaretype_software_device_software_type_hardware_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Название приоритета')),
            ],
            options={
                'verbose_name': 'Приоритет заявки',
                'verbose_name_plural': 'Приоритеты заявки',
                'db_table': 'ApplicationPriority',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявки',
                'db_table': 'ApplicationStatus',
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявки',
                'db_table': 'ApplicationType',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortDescription', models.CharField(default='', max_length=100, verbose_name='Тема обращения')),
                ('content', models.TextField(verbose_name='Содержимое заявки')),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='Test.branchofficelocation', verbose_name='Адрес')),
                ('applicant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='open_applications', to='Test.individualentity', verbose_name='Заявитель')),
                ('contractor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='Test.individualentity', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'Application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None, verbose_name='Дата и время действия')),
                ('content', models.TextField(default='', verbose_name='Описание действия')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Действие по заявке',
                'verbose_name_plural': 'Действия по заявке',
                'db_table': 'ApplicationActions',
            },
        ),
        migrations.CreateModel(
            name='ApplicationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='', verbose_name='Файл в заявке')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл в заявке',
                'verbose_name_plural': 'Файлы в заявке',
                'db_table': 'ApplicationFiles',
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None, verbose_name='Время отправления')),
                ('content', models.TextField(default='', verbose_name='Содержимое сообщения')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.application', verbose_name='Заявка')),
                ('sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение заявки',
                'verbose_name_plural': 'Сообщения заявки',
                'db_table': 'ApplicationMessages',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(verbose_name='Дата создания')),
                ('acceptanceDate', models.DateField(verbose_name='Дата принятия')),
                ('completionDate', models.DateField(verbose_name='Дата закрытия')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.application', verbose_name='Заявка')),
                ('priority', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.applicationpriority', verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'SLA заявки',
                'verbose_name_plural': 'SLA заявки',
                'db_table': 'ApplicationSLA',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.application', verbose_name='Заявка')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.device', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Предмет заявки',
                'verbose_name_plural': 'Предметы заявки',
                'db_table': 'ApplicationsSubjects',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='device',
            field=models.ManyToManyField(related_name='applications', through='Test.ApplicationSubject', to='Test.device', verbose_name='Оборудование по заявке'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicationType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.applicationtype', verbose_name='Тип заявки'),
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeTime', models.DateTimeField(default=None, verbose_name='Дата и время изменения')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.application', verbose_name='Заявка')),
                ('newApplicationStatus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.applicationstatus', verbose_name='Новый статус')),
            ],
            options={
                'verbose_name': 'История изменения статусов заявки',
                'verbose_name_plural': 'Истории изменения статусов заявок',
                'db_table': 'ApplicationStatusHistory',
                'constraints': [models.UniqueConstraint(fields=('application',), name='unique_application_status_history')],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationsubject',
            constraint=models.UniqueConstraint(fields=('application', 'device'), name='unique_application_device'),
        ),
    ]
