# Generated by Django 5.1.4 on 2024-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_alter_account_role_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ITN',
            field=models.CharField(default='', max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='decisionMaker',
            field=models.ManyToManyField(null=True, related_name='decision_maker_in_companies', through='Test.CompanyDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='decisionMaker',
            field=models.ManyToManyField(null=True, related_name='decision_maker_in_company_groups', through='Test.CompanyGroupDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
        migrations.AlterField(
            model_name='individualentity',
            name='ITN',
            field=models.CharField(default='', max_length=12, null=True, verbose_name='ИНН'),
        ),
    ]
