# Generated by Django 5.1.4 on 2024-12-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0012_alter_company_itn_alter_company_decisionmaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='decisionMaker',
            field=models.ManyToManyField(related_name='decision_maker_in_companies', through='Test.CompanyDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='decisionMaker',
            field=models.ManyToManyField(related_name='decision_maker_in_company_groups', through='Test.CompanyGroupDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
    ]
