# Generated by Django 5.1.4 on 2024-12-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_alter_company_decisionmaker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchofficelocation',
            options={'verbose_name': 'Помещение филиала', 'verbose_name_plural': 'Помещения филиала'},
        ),
        migrations.RemoveField(
            model_name='branchofficelocation',
            name='building',
        ),
        migrations.RemoveField(
            model_name='branchofficelocation',
            name='street',
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='building',
            field=models.CharField(default='', max_length=20, verbose_name='Строение\\здание'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='street',
            field=models.CharField(default='', max_length=20, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='branchofficelocation',
            name='room_name',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Название помещения'),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='note',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='branchofficelocation',
            name='room',
            field=models.CharField(default='', max_length=5, verbose_name='Номер помещения'),
        ),
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='note',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
    ]
