# Generated by Django 5.1.4 on 2024-12-29 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0014_alter_branchofficelocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.AddField(
            model_name='application',
            name='branch_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Test.branchoffice', verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Test.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Test.branchofficelocation', verbose_name='Помещение'),
            preserve_default=False,
        ),
    ]
