# Generated by Django 5.1.4 on 2024-12-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_remove_application_address_application_branch_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='license_key',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Лицензионный ключ'),
        ),
    ]
