# Generated by Django 5.1.4 on 2024-12-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0016_alter_software_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='factoryNumber',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='device',
            name='inventoryNumber',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='factoryNumber',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='inventoryNumber',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Инвентарный номер'),
        ),
    ]
