# Generated by Django 5.1.4 on 2024-12-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0018_alter_applicationactions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationactions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время действия'),
        ),
    ]
