# Generated by Django 5.1.4 on 2025-01-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0020_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationstatushistory',
            name='unique_application_status_history',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ManyToManyField(related_name='applications', through='Test.ApplicationStatusHistory', to='Test.applicationstatus', verbose_name='Статусы заявки'),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='changeTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения'),
        ),
    ]
