# Generated by Django 5.1.4 on 2025-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0022_alter_applicationsla_acceptancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='decisionMaker',
            field=models.ManyToManyField(blank=True, related_name='decision_maker_in_company_groups', through='Test.CompanyGroupDecisionMaker', to='Test.individualentity', verbose_name='ЛПР'),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Примечания'),
        ),
    ]
