# Generated by Django 5.1.4 on 2025-01-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0023_alter_branchoffice_note_alter_company_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='branchOffices',
        ),
        migrations.CreateModel(
            name='BranchOfficeEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchOffice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.branchoffice', verbose_name='Филиал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.individualentity', verbose_name='Учётная запись')),
            ],
            options={
                'verbose_name': 'M2M Человек-Филиал',
                'verbose_name_plural': 'M2M Человек-Филиал',
                'db_table': 'BranchEmployees',
            },
        ),
        migrations.AddField(
            model_name='individualentity',
            name='workplaces',
            field=models.ManyToManyField(related_name='individual_entities', through='Test.BranchOfficeEmployees', to='Test.branchoffice', verbose_name='Филиалы'),
        ),
        migrations.DeleteModel(
            name='AccountOfBranchEmployees',
        ),
        migrations.AddConstraint(
            model_name='branchofficeemployees',
            constraint=models.UniqueConstraint(fields=('employee', 'branchOffice'), name='unique_employee_branch_office'),
        ),
    ]
