# Generated by Django 5.1.4 on 2025-01-13 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0025_alter_branchofficeemployees_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOfficeEmployeeAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('branchOffice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.branchoffice', verbose_name='Филиал')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Test.individualentity', verbose_name='Владелец аккаунта')),
            ],
        ),
    ]
