# Generated by Django 5.1.4 on 2025-01-13 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0026_branchofficeemployeeaccounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchOfficeEmployeeAccounts',
            new_name='BranchOfficeAccounts',
        ),
        migrations.AlterModelOptions(
            name='branchofficeaccounts',
            options={'verbose_name': 'M2M Аккаунт-Филиал', 'verbose_name_plural': 'M2M Аккаунт-Филиал'},
        ),
        migrations.AddField(
            model_name='branchofficeemployees',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Test.position', verbose_name='Должность'),
        ),
        migrations.AddConstraint(
            model_name='branchofficeaccounts',
            constraint=models.UniqueConstraint(fields=('account', 'branchOffice'), name='unique_account_branch_office'),
        ),
        migrations.AlterModelTable(
            name='branchofficeaccounts',
            table='BranchOfficeAccounts',
        ),
    ]
