# Generated by Django 5.1.4 on 2025-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0027_rename_branchofficeemployeeaccounts_branchofficeaccounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='position',
        ),
        migrations.AddField(
            model_name='account',
            name='branchOffice',
            field=models.ManyToManyField(related_name='accounts', through='Test.BranchOfficeAccounts', to='Test.branchoffice', verbose_name='Филиал'),
        ),
    ]
