# Generated by Django 5.1.4 on 2025-01-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0028_remove_account_position_account_branchoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Примечания'),
        ),
    ]
