# Generated by Django 5.1.4 on 2025-01-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0029_alter_account_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualentity',
            name='INIPA',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Снилс'),
        ),
        migrations.AlterField(
            model_name='individualentity',
            name='ITN',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='individualentity',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Мужчина'), (1, 'Женщина'), (2, 'Не указан')], default=2, null=True, verbose_name='Пол'),
        ),
    ]
