# Generated by Django 5.1.4 on 2025-01-20 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0031_device_purchasedate_device_warrantyexpirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Test.deviceplacementmethod', verbose_name='Метод размещения'),
        ),
        migrations.AlterField(
            model_name='device',
            name='responsiblePerson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='Test.individualentity', verbose_name='Ответственное лицо'),
        ),
    ]
