# Generated by Django 5.1.4 on 2025-01-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0032_alter_device_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Модель'),
        ),
    ]
