# Generated by Django 5.1.4 on 2025-01-20 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0033_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceaction',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание действия'),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Test.softwaretype', verbose_name='Тип ПО'),
        ),
    ]
