# Generated by Django 5.1.4 on 2025-01-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0034_alter_maintenanceaction_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceaction',
            name='action_type',
        ),
        migrations.AddField(
            model_name='maintenanceaction',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='application_maintenance_actions', to='Test.application', verbose_name='Заявка'),
        ),
    ]
