# Generated by Django 5.1.4 on 2025-01-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0035_remove_maintenanceaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='installationDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='software',
            name='licenseActivationDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата активации лицензии'),
        ),
        migrations.AlterField(
            model_name='software',
            name='licenseExpirationDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания лицензии'),
        ),
        migrations.AlterField(
            model_name='software',
            name='purchaseDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата покупки'),
        ),
    ]
